### ISSUE TITLE
chatbot - set up env

### ISSUE THREAD

**Issue by jieunkxx** [thekimsplustwo/VanCityPropertyPulse#162]
Set up chat bot access for team members.
- [x] Adding users to Azure AD
- [x] Assign Bot Author and relevant roles
- [x] Validate Access
- [x] chat bot flow chart @pukkuKim

**Comment by czhaoca** [comment]
@jieunkxx @chris718 @pukkuKim @chohyeonkim 
Please check if you have access to the chatbot using the link in Slack
- [ ] Jieun
- [ ] Elly
- [ ] Ji Young
- [ ] Christina
