### ISSUE TITLE
Testing: Datadog Integration

### ISSUE THREAD

**Issue by jieunkxx** [thekimsplustwo/VanCityPropertyPulse#208]
- [x] #217
- [ ] backend unit test: @pukkuKim @chris718  
- [x] playwright / flow test: @jieunkxx #241 
- [ ] frontend / unit test: @chohyeonkim 

## write .yml

**Comment by czhaoca** [comment]
Invitation sent to all team members for datadog account to monitor production server's stats.

**Comment by czhaoca** [comment]
Please take a look of Datadog's Synthetic Monitoring capability. It can create automatic front end testing using chrome browser plug-in. Please check out short training produced by Datadog official team:
https://docs.datadoghq.com/synthetics/guide/synthetic-test-monitors/
https://learn.datadoghq.com/collections/ux-monitoring

<img width="1590" alt="Screenshot 2023-07-30 at 11 09 23 PM" src="https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/68087157/79e8e7d2-4123-47b1-9385-4a1b90108695">
