### ISSUE TITLE
bug: compare page rendering issue

### ISSUE THREAD

**Issue by czhaoca** [thekimsplustwo/VanCityPropertyPulse#215]
No data would show up when adding 2 or 3 items.
Error:
GET /properties/{zpid} 400 140.060 ms - 49
AxiosError: Request failed with status code 429
    at settle
<img width="1316" alt="Screenshot 2023-07-28 at 6 56 32 PM" src="https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/68087157/5ec16ea8-2913-493e-a560-edb7951bf24b">

- use compare API&redux: https://github.com/thekimsplustwo/VanCityPropertyPulse/pull/240

**Comment by czhaoca** [comment]
diagnosis:
In order to avoid too many requests in a given amount of time, you could consider implementing a delay between your requests. JavaScript's setTimeout function can be used to delay your requests.
possible solution:
adding delay mechanism to resolve the issue.

**Comment by jieunkxx** [comment]
@czhaoca 
try compare API
