### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by chohyeonkim** [thekimsplustwo/VanCityPropertyPulse#259]
![image](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/104462860/7a49727d-ba24-48fc-aa59-2408138f62ec)

![image](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/104462860/7e4ba9b7-36c9-4bfa-9b0f-9ba4ebbb398b)

after token expires, does not redirect user to login page ( Not a big issue for demo though?)

**Comment by jieunkxx** [comment]
token lasts for an hour. It won't be a big deal for demo.

**Comment by chohyeonkim** [comment]
then i will close issue for now <>
