### ISSUE TITLE
Mapbox: pin points previously stored property location instead of the current

### ISSUE THREAD

**Issue by jieunkxx** [thekimsplustwo/VanCityPropertyPulse#266]
- red pin points prev property location instead of the current location of the property

#### screenshots
![Screenshot 2023-08-03 at 10 59 00 PM](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/67996710/8235b6fd-3415-4319-b1ae-7c1acdfb27a1)

![Screenshot 2023-08-03 at 11 00 23 PM](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/67996710/72071987-86b8-430d-b03b-b2d0ca949692)

![Screenshot 2023-08-03 at 11 01 19 PM](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/67996710/fa7fc6b0-29aa-41ae-b79d-c8b9f2372dfe)

**Comment by chohyeonkim** [comment]
Sorry aren't they different locations?

**Comment by jieunkxx** [comment]
@chohyeonkim kitslano's mapbox pins to the previous, and Expo blvd has the kits's location
