### ISSUE TITLE
Detail Page : Price per SQFT data missing

### ISSUE THREAD

**Issue by chohyeonkim** [thekimsplustwo/VanCityPropertyPulse#283]
![image](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/104462860/7894db32-89e6-4b35-a5ea-ae2a406b7d3d)

not sure are these supposed to show up 'CAD'? with our any number let me know if am wrong!

**Comment by chris718** [comment]
@chohyeonkim Yes, if there's no data it will just show up 'CAD', but I can change it to make the whole body empty if there's no data for it. Which one do you think is better🧐?

**Comment by chohyeonkim** [comment]
@chris718 oh i was confused it wasnt showing up propertly . yes we can only shows the data when there is . Thanks
