### ISSUE TITLE
User page: Gap between user profile and Nearby Me

### ISSUE THREAD

**Issue by chohyeonkim** [thekimsplustwo/VanCityPropertyPulse#298]
am i only the one see the big gap here?

![image](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/104462860/046299db-dd02-4755-a88d-c37b043f755b)

**Comment by czhaoca** [comment]
I believe it can be fixed by turn off height in CSS
<img width="1202" alt="Screenshot 2023-08-06 at 7 35 26 AM" src="https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/68087157/9cfbc07f-f957-4684-91ae-e2115704086d">

**Comment by pukkuKim** [comment]
Thank you, guys! The PR has been created.
