### ISSUE TITLE
Home page: max price get reset to min price while editing the price (once it hits less than min)

### ISSUE THREAD

**Issue by jieunkxx** [thekimsplustwo/VanCityPropertyPulse#324]
https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/67996710/1af16666-5b77-4279-b24d-9f88651cf962

**Comment by chohyeonkim** [comment]
@jieunkxx I watched the video max price should not go lower than 13000( unless 0) , what would you like to do with the min/max?

**Comment by jieunkxx** [comment]
@chohyeonkim I was editing the max, not intended to put something lower than the min, but while editing my max, by deleting some number, whenever it hits the boundary, the number get reset to the min.
